service: serverless-http-api-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'

functions:
  test:
    handler: src/functions/test/handler.test
    events:
      - httpApi:
          path: /test
          method: get


plugins:
  - serverless-plugin-typescript
  - serverless-offline
