service: serverless-http-api-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: src/functions/teste/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  hello2:
    handler: src/functions/index.hello
    events:
      - httpApi:
          path: /dois
          method: get

  createProduct:
    handler: src/functions/product/create/handler.create
    events:
      - http:
          path: /products
          method: post
          cors: true


plugins:
  - serverless-plugin-typescript
  - serverless-offline
