name: Deploy Resource Manager

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

env:
  _STAGE: dev
  _REPOSITORY_NAME: github-action-nodejs-serverless

jobs:
  DeployServerless:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: npm install

      - name: Set deployment stage
        run: |
          if [ ${{ github.ref }} == 'refs/heads/main' ] || [ ${{ github.ref }} == 'refs/heads/master' ]; then
            echo "STAGE=production" >> $GITHUB_ENV
          elif [ ${{ github.ref }} == 'refs/heads/staging' ]; then
            echo "STAGE=staging" >> $GITHUB_ENV
          else
            echo "STAGE=dev" >> $GITHUB_ENV
          fi

      - name: Serverless deploy
        uses: serverless/github-action@v1
        with:
          args: deploy --stage ${STAGE}
        env:
          LOG_LEVEL: debug
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
